### ISSUE TITLE
Icon grid rather than auto-arrange when resizing

### ISSUE THREAD

**Issue by daltanious** [z-------------/New-New-Tab-Page#11]
Love this. Always use it, many co-workers dig it. I was wondering if there is a way to keep a certain grid, like a 3x10, which is what my monitor is arranged to. When I use my laptop, it goes into 3x8 + a 1x6 which doesn't look as organized due to colors. 
No biggie, I will still use this for months to come either way, I'm sure.
![good grid](https://user-images.githubusercontent.com/32861628/31648770-c8dede16-b2cc-11e7-9125-ae821532c2d7.png)
![not-so good grid](https://user-images.githubusercontent.com/32861628/31648771-c8f87768-b2cc-11e7-8137-fd7991927c49.png)

**Comment by z-------------** [comment]
Thanks for using NNTP and it's great to hear you're enjoying it. 

Commit 38f5cf03ac74d3429fc7d816de280d20357dd694 adds the functionality you suggested. It would be great if you could [download](https://github.com/z-------------/New-New-Tab-Page/archive/master.zip) or clone the latest version and see if it works right, and I'll be testing it myself as well. If everything is ok I'll release it on the Web Store soon.

Thanks again for your suggestion :)

**Comment by daltanious** [comment]
Fixed grid works great! Not sure what evaluation goes on; when I've got 30 icons and set the fixed column to 10 and the fixed row to 4, it shows the same if I set the row to 3. So for me it works how I want it either way and it's giving preference to the column value.

**Comment by z-------------** [comment]
Good to hear that it solves the issue. I'll push it to the Web Store as soon as I can.
