### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by TheRealNamikaze** [z-------------/New-New-Tab-Page#2]
When I'm using an icon for a custom "app" or link, usually the icons are out of place or distorted in some way.  I suspect the issue is related to icon size.  Does the New New Tab Page extension allow for scaling icons?  If not, what is the size of the icon that should be used?

**Comment by z-------------** [comment]
Hey TheRealNamikaze. In what way are the icons distorted? A screenshot would be best to help me understand the problem.

**Comment by TheRealNamikaze** [comment]
Hello there.  No worries - let me try changing the icon sizes first, to see if that fixes it.  It might just be that it's scaling funny because the original icons are not the right proportion.

Here's a screenshot though, with the original version of each icon below the one that comes out funny looking.

![screen](https://cloud.githubusercontent.com/assets/13359604/10808947/a861cc18-7db6-11e5-9bb5-4fabb1410d47.png)

**Comment by TheRealNamikaze** [comment]
Yup!  Tested by changing the logo size to 130x130, and it looks great now!  :+1:
