### ISSUE TITLE
How change weather location?

### ISSUE THREAD

**Issue by z1xx** [z-------------/New-New-Tab-Page#3]
I have variable IP address - every restart connection I have another IP. How to set up my current location (for weather) and not the location of the resulting IP address?

**Comment by z-------------** [comment]
Hello! This is currently not possible in New New Tab Page, though I'll be sure to add it soon. Thanks for suggesting this.

**Comment by z-------------** [comment]
Hey z1xx, 
If you're still interested, commit d3ffa5d adds the ability to use either GPS or specific coordinates for weather. Sorry this took so long.
