### ISSUE TITLE
open tiles in new tabs?

### ISSUE THREAD

**Issue by beautypersoni** [z-------------/New-New-Tab-Page#9]
First off, best new tab extension I've tried. Any chance for an option to open tiles in new tabs, right- or middle-click?

**Comment by z-------------** [comment]
Hey beautypersoni, thanks for the kind words.

I've just pushed an update to NNTP on the Chrome Web Store that fixes this functionality (an update to Chrome broke it a while back).

Sorry that this took so long. I hope you haven't given up on NNTP.

**Comment by z-------------** [comment]
Forgot to add: you can open shortcuts in a new tab by middle-clicking, ctrl-clicking, or cmd-clicking.
